# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/default', upload_to='avatar', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='昵称'),
        ),
    ]
