# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类别', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文章名', max_length=100)),
                ('body', models.TextField(help_text='文章内容')),
                ('created_time', models.DateTimeField(help_text='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, help_text='修改/更新时间')),
                ('excerpt', models.CharField(blank=True, help_text='摘要', max_length=200)),
                ('is_delete', models.BooleanField(default=False, help_text='删除标记')),
                ('views', models.PositiveIntegerField(default=0, help_text='文章阅读量')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名', max_length=100)),
            ],
        ),
    ]
