# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170827_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_img',
            field=models.ImageField(default='title_img/default.jpg', help_text='标题图片', upload_to='title_img'),
        ),
    ]
