# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 16:00
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(help_text='文章内容'),
        ),
    ]
